export const INFLUENCER_CATEGORIES = [
  "Fashion",
  "Beauty & Makeup",
  "Skincare",
  "Haircare",
  "Fitness & Gym",
  "Health & Wellness",
  "Nutrition & Diet",
  "Lifestyle",
  "Travel",
  "Food & Cooking",
  "Restaurants & Cafes",
  "Technology",
  "Gadgets & Electronics",
  "Gaming",
  "Business",
  "Entrepreneurship",
  "Finance & Investing",
  "Real Estate",
  "Education",
  "Career & Jobs",
  "Motivation & Self-Improvement",
  "Books & Literature",
  "Entertainment",
  "Movies & OTT",
  "Music",
  "Dance",
  "Comedy",
  "Art & Creativity",
  "Photography",
  "Videography",
  "Parenting & Family",
  "Kids & Baby",
  "Pets & Animals",
  "Automotive",
  "Sports",
  "Cricket",
  "Football",
  "Fashion & Jewelry",
  "Home & Interior",
  "Gardening",
  "DIY & Crafts",
  "Luxury & Premium Lifestyle",
  "Relationships & Dating",
  "Spirituality",
  "Culture & Tradition",
  "News & Current Affairs",
  "Politics & Public Affairs",
  "Social Causes",
  "Agriculture & Farming",
  "Sustainability & Environment",
  "Local/Regional Content",
  "Telugu Content",
  "Beauty & Fashion",
  "Wedding & Bridal",
  "Photography & Modeling",
  "Professional Services",
  "B2B & Industry",
  "Digital Marketing",
  "AI & Emerging Technology",
  "Science & Innovation",
] as const;

export const WEBSITE_CATEGORIES = [
  "Technology",
  "Software",
  "SaaS",
  "Trending",
  "Premium",
  "Premium PR",
  "Business",
  "Finance",
  "Finance Business",
  "Top Link",
  "Top Link Build",
  "Health",
  "News & Magazine",
  "Travel",
  "Lifestyle",
  "Internet",
  "Education",
  "Entertainment",
  "Real Estate",
  "Digital Marketing",
] as const;
