export const INFLUENCER_CATEGORIES = [
  "Fashion",
  "Beauty & Makeup",
  "Skincare",
  "Haircare",
  "Fitness & Gym",
  "Health & Wellness",
  "Nutrition & Diet",
  "Lifestyle",
  "Travel",
  "Food & Cooking",
  "Restaurants & Cafes",
  "Technology",
  "Gadgets & Electronics",
  "Gaming",
  "Business",
  "Entrepreneurship",
  "Finance & Investing",
  "Real Estate",
  "Education",
  "Career & Jobs",
  "Motivation & Self-Improvement",
  "Books & Literature",
  "Entertainment",
  "Movies & OTT",
  "Music",
  "Dance",
  "Comedy",
  "Art & Creativity",
  "Photography",
  "Videography",
  "Parenting & Family",
  "Kids & Baby",
  "Pets & Animals",
  "Automotive",
  "Sports",
  "Cricket",
  "Football",
  "Fashion & Jewelry",
  "Home & Interior",
  "Gardening",
  "DIY & Crafts",
  "Luxury & Premium Lifestyle",
  "Relationships & Dating",
  "Spirituality",
  "Culture & Tradition",
  "News & Current Affairs",
  "Politics & Public Affairs",
  "Social Causes",
  "Agriculture & Farming",
  "Sustainability & Environment",
  "Local/Regional Content",
  "Telugu Content",
  "Beauty & Fashion",
  "Wedding & Bridal",
  "Photography & Modeling",
  "Professional Services",
  "B2B & Industry",
  "Digital Marketing",
  "AI & Emerging Technology",
  "Science & Innovation",
] as const;

export const WEBSITE_CATEGORIES = [
  "Technology",
  "Artificial Intelligence",
  "Software & SaaS",
  "IT Services",
  "Business",
  "Finance",
  "Banking",
  "FinTech",
  "Insurance",
  "Investment",
  "Education",
  "E-learning",
  "Healthcare",
  "Medical",
  "Fitness",
  "Lifestyle",
  "Fashion",
  "Beauty",
  "Travel & Tourism",
  "Food & Restaurants",
  "Real Estate",
  "Automotive",
  "E-commerce",
  "Retail",
  "Entertainment",
  "Media",
  "News",
  "Sports",
  "Gaming",
  "Marketing & Advertising",
  "Digital Marketing",
  "Human Resources & Recruitment",
  "Legal",
  "Consulting",
  "Manufacturing",
  "Construction",
  "Electronics",
  "Telecommunications",
  "Agriculture",
  "Government & Public Services",
  "Non-Profit / NGO",
  "Events",
  "Photography",
  "Music",
  "Books & Publishing",
  "Parenting",
  "Pets",
  "Home & Interior",
  "Luxury",
  "Personal Development",
  "Careers & Jobs",
  "Cryptocurrency & Blockchain",
  "Startups & Entrepreneurship",
  "Other",
] as const;

